// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Martin Schröder <info@swedishembedded.com>
//
// Swedish Embedded AB implements learning agents that acquire a capability
// from a document and prove it with evidence, for its clients. If your team
// needs expertise in continual learning or agent evaluation, you can
// procure our services by sending an email to info@swedishembedded.com.

//! Spec: `learn` over a document runs every stage as one recorded run -
//! the source captured, tasks generated by the policy and admitted by code,
//! each solved and graded by its kind's verifier, a failure critiqued and
//! retried, and the passing answers written as an sft-final dataset the
//! trainer's own parser accepts - and hands that dataset to training, whose
//! candidate is reported and not released. `--dry-run` writes nothing.
//!
//! The policy is a scripted in-test model and code runs in the process
//! sandbox; training is a test double, since training needs weights.

// Helpers outside a #[test] fn unwrap too: a panic is the failure report.
#![allow(clippy::unwrap_used)]

mod common;

use std::sync::Mutex;

use common::{scratch_context, Scripted};
use serde_json::json;
use splinter_campaign::learn::{learn, LearnRequest, Learned};
use splinter_campaign::train::{Candidate, TrainRequest, Trainer};
use splinter_campaign::{CampaignError, Context};
use splinter_policy::train::HeldOutScore;
use splinter_store::runs::{read_run, RunStatus};
use splinter_views::{DatasetId, StoredDataset};
use sven_sdk::CancelToken;

const MANUAL: &str = "# Frobnicator manual

The Frobnicator is a bench power controller.

## Console

The console UART of the Frobnicator runs at 115200 baud with eight data bits.

## Power

The Frobnicator draws 40 mA when idle and 900 mA at full load.
";

/// The policy: writes two recall tasks when asked for tasks, answers the
/// baud rate right and the idle current wrong until it is given feedback,
/// and critiques a failed attempt.
fn policy() -> Scripted {
    Scripted::new(|prompt| {
        if prompt.contains("You write training tasks") {
            json!({ "tasks": [
                {
                    "instruction": "At what baud rate does the Frobnicator console UART run?",
                    "reference": "115200 baud",
                    "evidence": [{ "section": 1, "quote": "runs at 115200 baud" }]
                },
                {
                    "instruction": "How much current does the Frobnicator draw when idle?",
                    "reference": "40 mA",
                    "evidence": [{ "section": 2, "quote": "40 mA when idle" }]
                }
            ]})
            .to_string()
        } else if prompt.contains("You are reviewing an attempt") {
            "The idle current is wrong: it is not what the power specification gives.".into()
        } else if prompt.contains("baud rate") {
            "115200 baud".into()
        } else if prompt.contains("Feedback on an earlier attempt") {
            "40 mA".into()
        } else {
            "12 mA".into()
        }
    })
}

/// Training as a test double: keeps what it was handed.
#[derive(Default)]
struct RecordingTrainer {
    handed: Mutex<Vec<DatasetId>>,
}

impl Trainer for RecordingTrainer {
    fn train(
        &self,
        _ctx: &Context,
        request: &TrainRequest,
        datasets: &[StoredDataset],
        _cancel: &CancelToken,
    ) -> Result<Candidate, CampaignError> {
        let ids: Vec<DatasetId> = datasets.iter().map(|d| d.id.clone()).collect();
        self.handed.lock().unwrap().extend(ids.clone());
        let unscored = HeldOutScore {
            loss: None,
            token_accuracy: None,
            positions: 0,
            records: 0,
            skipped: 0,
        };
        Ok(Candidate {
            candidate: "candidate-test".into(),
            from: request.from.to_string(),
            datasets: ids,
            replay: None,
            adapter: "adapter.safetensors".into(),
            adapter_digest: "sha256:test".into(),
            base_score: unscored,
            tuned_score: unscored,
            records: 0,
            released: false,
        })
    }
}

#[test]
fn learn_runs_every_stage_to_a_trainable_dataset_and_an_unreleased_candidate() {
    let (scratch, ctx) = scratch_context("learn", policy(), false);
    let manual = scratch.0.join("manual.md");
    std::fs::write(&manual, MANUAL).unwrap();
    let trainer = RecordingTrainer::default();

    let learned = learn(
        &ctx,
        &LearnRequest {
            sources: vec![manual.display().to_string()],
            goal: Some("know the Frobnicator's electrical limits".into()),
            ..LearnRequest::default()
        },
        &trainer,
    )
    .unwrap();
    let Learned::Ran(run) = learned else {
        panic!("a learn that is not a dry run runs");
    };
    let report = &run.report;
    assert_eq!(report.stopped, None, "{report:#?}");
    assert_eq!(report.sources.len(), 1);
    assert_eq!(report.sources[0].kind, "document");
    let tasks = report.tasks.as_ref().unwrap();
    assert_eq!(tasks.tasks, 2, "{tasks:#?}");
    let solved = report.solve.as_ref().unwrap();
    assert_eq!((solved.solved, solved.answered), (2, 2), "{solved:#?}");
    assert_eq!(solved.solver, common::POLICY);
    let verified = report.verify.as_ref().unwrap();
    assert_eq!((verified.passed, verified.failed), (1, 1), "{verified:#?}");
    let critiqued = report.critique.as_ref().unwrap();
    assert_eq!(
        (critiqued.critiqued, critiqued.repaired),
        (1, 1),
        "{critiqued:#?}"
    );

    let dataset = report.dataset.as_ref().unwrap();
    assert_eq!(dataset.view, "sft-final");
    assert_eq!(
        dataset.records, 2,
        "the right first answer and the repaired one"
    );
    let text = std::fs::read_to_string(&dataset.path).unwrap();
    assert!(
        text.contains("115200 baud") && text.contains("40 mA"),
        "{text}"
    );
    assert!(
        !text.contains("12 mA"),
        "a failed answer is never trained on"
    );
    assert!(
        !text.contains("Feedback on an earlier attempt"),
        "the critique is teacher-only: {text}"
    );
    splinter_policy::train::validate_dataset(&dataset.path).unwrap();

    assert_eq!(
        *trainer.handed.lock().unwrap(),
        vec![dataset.dataset.clone()]
    );
    let candidate = report.candidate.as_ref().unwrap();
    assert!(!candidate.released, "training never releases");

    let recorded = read_run(ctx.root(), &run.run).unwrap();
    assert_eq!(recorded.status, RunStatus::Completed);
    let stages: Vec<&str> = recorded.stages.iter().map(|s| s.stage.as_str()).collect();
    assert_eq!(
        stages,
        ["sources", "tasks", "solve", "verify", "critique", "dataset", "train"]
    );
}

#[test]
fn a_dry_run_reports_the_plan_and_writes_nothing() {
    let (scratch, ctx) = scratch_context("learn-dry", policy(), false);
    let manual = scratch.0.join("manual.md");
    std::fs::write(&manual, MANUAL).unwrap();
    let trainer = RecordingTrainer::default();

    let learned = learn(
        &ctx,
        &LearnRequest {
            sources: vec![manual.display().to_string()],
            kinds: vec!["recall".into(), "denoise".into()],
            dry_run: true,
            ..LearnRequest::default()
        },
        &trainer,
    )
    .unwrap();
    let Learned::Planned(plan) = learned else {
        panic!("a dry run only plans");
    };
    assert!(plan.dry_run);
    assert_eq!(plan.kinds, ["recall", "denoise"]);
    assert_eq!(plan.stages.len(), 7);
    assert!(
        !ctx.root().path().exists(),
        "a dry run writes nothing under the state root"
    );
    assert!(trainer.handed.lock().unwrap().is_empty());

    let refused = learn(
        &ctx,
        &LearnRequest {
            sources: vec![manual.display().to_string()],
            kinds: vec!["recal".into()],
            dry_run: true,
            ..LearnRequest::default()
        },
        &trainer,
    )
    .unwrap_err();
    assert!(refused.is_refusal(), "{refused}");
}
