// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Martin Schröder <info@swedishembedded.com>
//
// Swedish Embedded AB implements learning agents that acquire a capability
// from a document and prove it with evidence, for its clients. If your team
// needs expertise in continual learning or agent evaluation, you can
// procure our services by sending an email to info@swedishembedded.com.

//! Spec: `learn` over a document runs every stage as one recorded run -
//! the policy resolved once and recorded, the source captured, tasks
//! generated by the policy and admitted by code, each solved and graded by
//! its kind's verifier, a failure critiqued and retried, and the passing
//! answers written as an sft-final dataset the trainer's own parser
//! accepts - hands that dataset to training, and puts the candidate
//! through the release gate, which releases nothing it cannot measure.
//! The release `policy:default` resolved to when the run started is the
//! one the whole run uses, however the alias moves. `--dry-run` writes
//! nothing.
//!
//! The policy is a scripted in-test model and code runs in the process
//! sandbox; training is a test double, since training needs weights.

// Helpers outside a #[test] fn unwrap too: a panic is the failure report.
#![allow(clippy::unwrap_used)]

mod common;

use std::sync::Mutex;

use std::path::PathBuf;
use std::sync::Arc;

use common::gate::{anchor_file, gate_context, put_base, released, Brain, FakeTrainer, ANCHOR};
use common::manual::{manual_policy as policy, MANUAL};
use common::{scratch_context, Scripted};
use splinter_agent::solve::Model;
use splinter_agent::CancelToken;
use splinter_core::dataset::DatasetId;
use splinter_core::model_ref::ModelRef;
use splinter_core::release::ReleaseId;
use splinter_model::train::{Trained, TrainedPreference};
use splinter_model::ModelSelection;
use splinter_orchestrator::{Context, OrchestratorError};
use splinter_pipelines::exam::{examine, Exam, ExamineRequest};
use splinter_pipelines::learn::{learn, LearnRequest, Learned};
use splinter_pipelines::release::{anchor, rollback};
use splinter_pipelines::train::{TrainPlan, Trainer};
use splinter_store::runs::{read_run, RunStatus};

/// Training as a test double: keeps what it was handed, and trains the
/// fixtures' fake adapter.
#[derive(Default)]
struct RecordingTrainer {
    handed: Mutex<Vec<DatasetId>>,
}

impl Trainer for RecordingTrainer {
    fn train(
        &self,
        ctx: &Context,
        plan: &TrainPlan,
        cancel: &CancelToken,
    ) -> Result<Trained, OrchestratorError> {
        self.handed
            .lock()
            .unwrap()
            .extend(plan.datasets.iter().map(|d| d.id.clone()));
        FakeTrainer::knowing(&[]).train(ctx, plan, cancel)
    }

    fn train_preference(
        &self,
        ctx: &Context,
        plan: &TrainPlan,
        cancel: &CancelToken,
    ) -> Result<TrainedPreference, OrchestratorError> {
        self.handed
            .lock()
            .unwrap()
            .extend(plan.datasets.iter().map(|d| d.id.clone()));
        FakeTrainer::knowing(&[]).train_preference(ctx, plan, cancel)
    }
}

#[test]
fn learn_runs_every_stage_to_a_trainable_dataset_and_an_unreleased_candidate() {
    let (scratch, ctx) = scratch_context("learn", policy(), false);
    put_base(&ctx);
    let manual = scratch.0.join("manual.md");
    std::fs::write(&manual, MANUAL).unwrap();
    let trainer = RecordingTrainer::default();

    let learned = learn(
        &ctx,
        &LearnRequest {
            sources: vec![manual.display().to_string()],
            goal: Some("know the Frobnicator's electrical limits".into()),
            // This spec is the pipeline's plumbing over a policy that
            // answers each task the same way every time: every task stays.
            no_frontier: true,
            ..LearnRequest::default()
        },
        &trainer,
    )
    .unwrap();
    let Learned::Ran(run) = learned else {
        panic!("a learn that is not a dry run runs");
    };
    let report = &run.report;
    assert_eq!(report.stopped, None, "{report:#?}");
    assert_eq!(report.sources.len(), 1);
    assert_eq!(report.sources[0].kind, "document");
    let tasks = report.tasks.as_ref().unwrap();
    assert_eq!(tasks.tasks, 2, "{tasks:#?}");
    let solved = report.solve.as_ref().unwrap();
    assert_eq!((solved.solved, solved.answered), (2, 2), "{solved:#?}");
    assert_eq!(solved.solver, common::POLICY);
    let verified = report.verify.as_ref().unwrap();
    assert_eq!((verified.passed, verified.failed), (1, 1), "{verified:#?}");
    let critiqued = report.critique.as_ref().unwrap();
    assert_eq!(
        (critiqued.critiqued, critiqued.repaired),
        (1, 1),
        "{critiqued:#?}"
    );

    let dataset = report.dataset.as_ref().unwrap();
    assert_eq!(dataset.view, "sft-final");
    assert_eq!(
        dataset.records, 2,
        "the right first answer and the repaired one"
    );
    let text = std::fs::read_to_string(&dataset.path).unwrap();
    assert!(
        text.contains("115200 baud") && text.contains("40 mA"),
        "{text}"
    );
    assert!(
        !text.contains("12 mA"),
        "a failed answer is never trained on"
    );
    assert!(
        !text.contains("Feedback on an earlier attempt"),
        "the critique is teacher-only: {text}"
    );
    splinter_model::train::validate_dataset(&dataset.path).unwrap();

    assert_eq!(
        *trainer.handed.lock().unwrap(),
        vec![dataset.dataset.clone()]
    );
    assert!(report.candidate.is_some());
    assert!(
        ctx.releases().list().unwrap().is_empty(),
        "training never releases"
    );
    assert_eq!(report.policy.release, None, "no release yet: the base");

    // The gate ran, and released nothing it could not measure: no anchor
    // suite, no brain, and the base's arm is no model here.
    let gated = report.release.as_ref().unwrap();
    assert!(!gated.gate.passed && gated.release.is_none(), "{gated:#?}");
    assert!(gated.gate.anchor.measured.is_none());
    assert!(gated.gate.serve.measured.is_none());
    assert!(!report.finished(true) && report.finished(false));
    // With no assistant configured the policy would be its own judge, which
    // a judge refuses; the exam says why it did not run and the gate decides.
    let Some(splinter_pipelines::exam::Exam::NotRun(why)) = &report.exam else {
        panic!("the exam could not run: {:?}", report.exam);
    };
    assert!(why.contains("refuses to grade"), "{why}");

    // The exam is also a command on a stored candidate, with the judge named.
    // This judge says PASS to everything, so it cannot be trusted: the exam
    // runs, calibrates it on controls made from the references of the tasks
    // the candidate was trained on, and makes no claim from it.
    let judge: ModelRef = "local:judge/pass".parse().unwrap();
    ctx.add_model(
        judge.clone(),
        Model::new(
            Arc::new(Scripted::new(|_| "PASS\nit does".into())),
            "scripted/judge",
        ),
    );
    // The exam measures the candidate against the base it continued.
    ctx.add_model(
        splinter_pipelines::release::arm(ctx.config(), None),
        Model::new(Arc::new(policy()), common::POLICY),
    );
    let id = &report.candidate.as_ref().unwrap().candidate;
    let Exam::Ran(examined) = examine(
        &ctx,
        &ExamineRequest {
            candidate: id,
            base: None,
            judge: Some(&judge),
            prompted: None,
            retrieval: None,
        },
        &CancelToken::new(),
    )
    .unwrap() else {
        panic!("the exam of a stored candidate runs");
    };
    assert!(examined.judge.controls > 0, "{examined:#?}");
    assert!(!examined.judge.trusted && examined.paired.is_none());

    let recorded = read_run(ctx.workspace(), &run.run).unwrap();
    assert_eq!(recorded.status, RunStatus::Completed);
    let stages: Vec<&str> = recorded.stages.iter().map(|s| s.stage.as_str()).collect();
    assert_eq!(
        stages,
        [
            "policy", "sources", "tasks", "solve", "verify", "teach", "variants", "critique",
            "select", "dataset", "train", "exam", "release"
        ]
    );
}

#[test]
fn a_dry_run_reports_the_plan_and_writes_nothing() {
    let (scratch, ctx) = scratch_context("learn-dry", policy(), false);
    let manual = scratch.0.join("manual.md");
    std::fs::write(&manual, MANUAL).unwrap();
    let trainer = RecordingTrainer::default();

    let learned = learn(
        &ctx,
        &LearnRequest {
            sources: vec![manual.display().to_string()],
            kinds: vec!["recall".into(), "denoise".into()],
            dry_run: true,
            ..LearnRequest::default()
        },
        &trainer,
    )
    .unwrap();
    let Learned::Planned(plan) = learned else {
        panic!("a dry run only plans");
    };
    assert!(plan.dry_run);
    assert_eq!(plan.kinds, ["recall", "denoise"]);
    assert_eq!(plan.stages.len(), 14);
    assert!(plan.stages.contains(&"variants"));
    assert!(
        plan.stages.contains(&"frontier"),
        "frontier selection is the default"
    );
    assert!(
        !ctx.root().path().exists(),
        "a dry run writes nothing under the state root"
    );
    assert!(trainer.handed.lock().unwrap().is_empty());

    let refused = learn(
        &ctx,
        &LearnRequest {
            sources: vec![manual.display().to_string()],
            kinds: vec!["recal".into()],
            dry_run: true,
            ..LearnRequest::default()
        },
        &trainer,
    )
    .unwrap_err();
    assert!(refused.is_refusal(), "{refused}");
}

/// A trainer that moves `default` from `from` to `to` while it trains, and
/// keeps its plan and what `policy:default` resolved to after the move.
struct AliasMover {
    from: ReleaseId,
    to: ReleaseId,
    seen: Mutex<Option<(TrainPlan, Option<PathBuf>)>>,
}

impl Trainer for AliasMover {
    fn train(
        &self,
        ctx: &Context,
        plan: &TrainPlan,
        cancel: &CancelToken,
    ) -> Result<Trained, OrchestratorError> {
        ctx.releases()
            .move_alias(
                "default",
                Some(&self.from),
                &self.to,
                "2026-09-30T08:00:00.000Z",
            )
            .unwrap();
        let ModelSelection::Local(weights) = ctx.selection(&ModelRef::policy_default()).unwrap()
        else {
            panic!("the policy is local");
        };
        *self.seen.lock().unwrap() = Some((plan.clone(), weights.adapter));
        FakeTrainer::knowing(&[]).train(ctx, plan, cancel)
    }

    fn train_preference(
        &self,
        _ctx: &Context,
        _plan: &TrainPlan,
        _cancel: &CancelToken,
    ) -> Result<TrainedPreference, OrchestratorError> {
        panic!("learn trains chat datasets only")
    }
}

#[test]
fn the_policy_is_resolved_once_when_a_run_starts_and_recorded() {
    let (scratch, ctx) = gate_context("learn-pin", Brain::Honest);
    anchor::freeze(&ctx, &anchor_file(&scratch.0, 4)).unwrap();
    let first = released(&ctx, "alpha", &[ANCHOR, "alpha"]);
    let second = released(&ctx, "beta", &[ANCHOR, "alpha", "beta"]);
    rollback(&ctx, "default").unwrap();
    ctx.add_model(
        ModelRef::policy_default(),
        Model::new(Arc::new(policy()), common::POLICY),
    );
    let manual = scratch.0.join("manual.md");
    std::fs::write(&manual, MANUAL).unwrap();
    let mover = AliasMover {
        from: first.clone(),
        to: second.clone(),
        seen: Mutex::new(None),
    };

    let learned = learn(
        &ctx,
        &LearnRequest {
            sources: vec![manual.display().to_string()],
            no_release: true,
            no_frontier: true,
            ..LearnRequest::default()
        },
        &mover,
    )
    .unwrap();
    let Learned::Ran(run) = learned else {
        panic!("a learn that is not a dry run runs");
    };

    let store = ctx.releases();
    assert_eq!(
        store.alias("default").unwrap(),
        Some(second),
        "the alias did move"
    );
    let first_adapter = store.get(&first).unwrap().adapter;
    let (plan, resolved_after_move) = mover.seen.lock().unwrap().clone().unwrap();
    assert_eq!(plan.parent, Some(first.clone()));
    assert_eq!(plan.continue_from.as_ref(), Some(&first_adapter));
    assert_eq!(
        resolved_after_move,
        Some(first_adapter),
        "the run keeps the release it started with"
    );
    assert_eq!(run.report.policy.release, Some(first.clone()));
    assert_eq!(
        run.report.candidate.as_ref().unwrap().parent,
        Some(first.clone())
    );
    assert!(run.report.release.is_none(), "--no-release");

    let recorded = read_run(ctx.workspace(), &run.run).unwrap();
    assert_eq!(recorded.stages[0].stage, "policy");
    assert_eq!(recorded.stages[0].summary["release"], first.to_string());
    assert!(recorded.stages.iter().all(|s| s.stage != "release"));
}

/// A run that admits no task says why each proposal was turned away, down
/// to the model's own reply, not only how many were.
#[test]
fn a_run_that_admits_nothing_reports_why_each_proposal_was_rejected() {
    let unparseable = common::Scripted::new(|_| "Sure! Here are some tasks.".into());
    let (scratch, ctx) = scratch_context("learn-rejections", unparseable, false);
    let manual = scratch.0.join("manual.md");
    std::fs::write(&manual, MANUAL).unwrap();
    let learned = learn(
        &ctx,
        &LearnRequest {
            sources: vec![manual.display().to_string()],
            ..LearnRequest::default()
        },
        &RecordingTrainer::default(),
    )
    .unwrap();
    let Learned::Ran(run) = learned else {
        panic!("a learn that is not a dry run runs");
    };
    let tasks = run.report.tasks.as_ref().unwrap();
    assert_eq!(tasks.tasks, 0, "{tasks:#?}");
    assert!(!tasks.rejections.is_empty(), "{tasks:#?}");
    for rejection in &tasks.rejections {
        assert_eq!(
            (rejection.kind.as_str(), rejection.reason.as_str()),
            ("recall", "malformed")
        );
        assert!(
            rejection.detail.contains("Sure! Here are some tasks."),
            "{rejection:#?}"
        );
    }
}
